openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: http://localhost:5000

paths:
  /api/auth/register:
    post:
      operationId: registerUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          $ref: "#/components/responses/RegisterResponse"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "409":
          $ref: "#/components/responses/EmailExists"

  /api/auth/confirm-email:
    post:
      operationId: confirmEmail
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfirmEmailRequest"
      responses:
        "200":
          $ref: "#/components/responses/ConfirmEmailResponse"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "404":
          $ref: "#/components/responses/UserNotFound"
        "422":
          $ref: "#/components/responses/InvalidCode"

  /api/auth/login:
    post:
      operationId: loginUser
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse"
        "401":
          $ref: "#/components/responses/InvalidCredentials"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "403":
          $ref: "#/components/responses/EmailNotConfirmed"

  /api/auth/refresh:
    post:
      operationId: refreshToken
      tags:
        - auth
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"

  /api/auth/google:
    post:
      operationId: googleAuth
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleAuthRequest"
      responses:
        "200":
          $ref: "#/components/responses/AuthResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "400":
          $ref: "#/components/responses/InvalidInput"

  /api/auth/logout:
    post:
      operationId: logoutUser
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully logged out"
        "401":
          $ref: "#/components/responses/InvalidToken"

  /api/auth/logout-all:
    post:
      operationId: logoutAllDevices
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logout from all devices successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully logged out from all devices"
        "401":
          $ref: "#/components/responses/InvalidToken"

components:
  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
        name:
          type: string

    RegisterResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Confirmation code sent to your email"

    ConfirmEmailRequest:
      type: object
      required:
        - email
        - code
      properties:
        email:
          type: string
          format: email
        code:
          type: string
          minLength: 6
          maxLength: 6

    ConfirmEmailResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Email confirmed successfully"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    GoogleAuthRequest:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: Google ID token

    User:
      type: object
      required:
        - id
        - email
        - name
        - activeRole
        - isEmailConfirmed
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        activeRole:
          type: string
          enum: [TRAINER, TRAINEE, PARENT, ADMIN, SUPERADMIN]
        isEmailConfirmed:
          type: boolean

    AuthResponse:
      type: object
      required:
        - accessToken
        - user
      properties:
        accessToken:
          type: string
        user:
          $ref: "#/components/schemas/User"

  responses:
    AuthResponse:
      description: Authentication successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthResponse"

    RegisterResponse:
      description: Registration successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RegisterResponse"

    ConfirmEmailResponse:
      description: Email confirmation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConfirmEmailResponse"

    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid input data"

    InvalidCredentials:
      description: Invalid credentials
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid email or password"

    InvalidToken:
      description: Invalid token
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid token"

    EmailExists:
      description: Email already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Email already registered"

    UserNotFound:
      description: User not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "User not found"

    InvalidCode:
      description: Invalid confirmation code
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid confirmation code"

    EmailNotConfirmed:
      description: Email not confirmed
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Please confirm your email first" 