openapi: 3.0.0
info:
  title: Trainer API
  version: 1.0.0
servers:
  - url: http://localhost:5000

paths:
  /api/trainer/me:
    get:
      operationId: getTrainerProfile
      tags:
        - profiles
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Trainer profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainerProfile"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/ProfileNotFound"

  /api/trainer/profile:
    post:
      operationId: createTrainerProfile
      tags:
        - profiles
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTrainerProfileRequest"
      responses:
        "200":
          description: Profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainerProfileId"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "409":
          $ref: "#/components/responses/ProfileExists"

    delete:
      operationId: deleteTrainerProfile
      tags:
        - profiles
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Profile deleted successfully
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/ProfileNotFound"

components:
  schemas:
    TrainerProfileId:
      type: object
      required:
        - id
      properties:
        id:
          type: string

    TrainerProfile:
      type: object
      required:
        - id
        - userId
      properties:
        id:
          type: string
        userId:
          type: string

    CreateTrainerProfileRequest:
      type: object
      properties:
        specialization:
          type: string
        experience:
          type: integer
        description:
          type: string
        achievements:
          type: array
          items:
            type: string

  responses:
    InvalidToken:
      description: Invalid token
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid token"

    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid input data"

    ProfileNotFound:
      description: Profile not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Profile not found"

    ProfileExists:
      description: Profile already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Profile already exists" 