openapi: 3.0.0
info:
  title: Trainer API
  version: 1.0.0
servers:
  - url: http://localhost:5001

paths:
  /api/trainer/me:
    get:
      operationId: getTrainerProfile
      tags:
        - profiles
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Trainer profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainerProfile"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/ProfileNotFound"

  /api/trainer/profile:
    post:
      operationId: createTrainerProfile
      tags:
        - profiles
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTrainerProfileRequest"
      responses:
        "200":
          description: Profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainerProfileId"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "409":
          $ref: "#/components/responses/ProfileExists"

    delete:
      operationId: deleteTrainerProfile
      tags:
        - profiles
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Profile deleted successfully
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/ProfileNotFound"

  /api/trainer/scan-qr:
    post:
      operationId: scanTrainee
      tags:
        - trainer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScanTraineeRequest"
      responses:
        "200":
          description: Trainee scan result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScanTraineeResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/TraineeNotFound"

  /api/trainer/scan-qr-and-create:
    post:
      operationId: scanAndCreateTraining
      tags:
        - trainer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScanAndCreateRequest"
      responses:
        "200":
          description: Training created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTrainingResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/TraineeNotFound"

  /api/trainer/attach-to-existing:
    post:
      operationId: attachToExistingTraining
      tags:
        - trainer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttachToTrainingRequest"
      responses:
        "200":
          description: Trainee attached successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttachToTrainingResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "404":
          $ref: "#/components/responses/TraineeNotFound"
        "403":
          $ref: "#/components/responses/InvalidTrainingAccess"

components:
  schemas:
    TrainerProfileId:
      type: object
      required:
        - id
      properties:
        id:
          type: string

    TrainerProfile:
      type: object
      required:
        - id
        - userId
      properties:
        id:
          type: string
        userId:
          type: string

    CreateTrainerProfileRequest:
      type: object
      properties:
        specialization:
          type: string
        experience:
          type: integer
        description:
          type: string
        achievements:
          type: array
          items:
            type: string

    ScanTraineeRequest:
      type: object
      required:
        - traineeUsername
      properties:
        traineeUsername:
          type: string

    ScanAndCreateRequest:
      type: object
      required:
        - traineeUsername
      properties:
        traineeUsername:
          type: string
        training:
          type: object
          properties:
            type:
              type: string
              enum: [INDIVIDUAL, GROUP]
            date:
              type: string
              format: date-time
            durationMin:
              type: integer
            gymId:
              type: string
            groupId:
              type: string
            templateId:
              type: string

    ScanTraineeResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [noActiveTraining, traineeAlreadyRecorded, traineeRecordedSuccessfully, specifyTraining]
        trainings: 
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
              startDate:
                type: string
                format: date-time
              name:
                type: string

    CreateTrainingResponse:
      type: object
      required:
        - status
        - trainingId
        - traineeAdded
      properties:
        status:
          type: string
          enum: [trainingCreated]
        trainingId:
          type: string
        traineeAdded:
          type: boolean

    AttachToTrainingRequest:
      type: object
      required:
        - trainingId
        - traineeUsername
      properties:
        trainingId:
          type: string
        traineeUsername:
          type: string

    AttachToTrainingResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [added_to_existing_training]

  responses:
    InvalidToken:
      description: Invalid token
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid token"

    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid input data"

    ProfileNotFound:
      description: Profile not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Profile not found"

    ProfileExists:
      description: Profile already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Profile already exists"

    TraineeNotFound:
      description: Trainee not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Trainee not found"

    InvalidTrainingAccess:
      description: Invalid training access
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "You don't have access to this training" 