openapi: 3.0.0
info:
  title: User Roles API
  version: 1.0.0
servers:
  - url: http://localhost:5001

paths:
  /api/users/me:
    get:
      operationId: getCurrentUser
      tags:
        - users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Current user information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"

  /api/users/me/onboarding:
    get:
      operationId: getUserOnboarding
      tags:
        - users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User onboarding status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OnboardingResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"

  /api/users/me/lang:
    patch:
      operationId: updateUserLanguage
      tags:
        - users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLanguageRequest"
      responses:
        "200":
          description: Language updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Language updated successfully"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "400":
          $ref: "#/components/responses/InvalidInput"

  /api/users/me/role:
    patch:
      operationId: updateUserRole
      tags:
        - users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateRoleRequest"
      responses:
        "200":
          description: Role updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Role updated successfully"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "403":
          $ref: "#/components/responses/InvalidRole"

  /api/users/me/role/init:
    post:
      operationId: initializeUserRole
      tags:
        - users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InitializeRoleRequest"
      responses:
        "200":
          description: Role initialized successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InitializeRoleResponse"
        "401":
          $ref: "#/components/responses/InvalidToken"
        "400":
          $ref: "#/components/responses/InvalidInput"

components:
  schemas:
    UserResponse:
      type: object
      required:
        - id
        - email
        - preferredLang
        - activeRole
        - roles
        - trainerProfile
        - traineeProfile
        - parentProfile
        - trainerStepsLeft
        - traineeStepsLeft
        - parentStepsLeft
      properties:
        id:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        preferredLang:
          type: string
          enum: [EN, UA, PL]
        activeRole:
          type: string
          enum: [TRAINER, TRAINEE, PARENT, ADMIN]
        roles:
          type: array
          items:
            type: string
            enum: [TRAINER, TRAINEE, PARENT, ADMIN]
        trainerStepsLeft:
          type: array
          items:
            type: string
          nullable: true
        traineeStepsLeft:
          type: array
          items:
            type: string
          nullable: true
        parentStepsLeft:
          nullable: true
          type: array
          items:
            type: string
        trainerProfile:
          $ref: "#/components/schemas/TrainerProfile"
        traineeProfile:
          $ref: "#/components/schemas/TraineeProfile"
        parentProfile:
          $ref: "#/components/schemas/ParentProfile"

    TrainerProfile:
      nullable: true
      type: object
      properties:
        gyms:
          type: array
          items:
            type: string
        groups:
          type: array
          items:
            type: string
        trainings:
          type: array
          items:
            type: string
        isOnboardingCompleted:
          type: boolean
        subscriptions:
          type: array
          items:
            type: string

    # TODO: add other fields
    TraineeProfile:
      nullable: true
      type: object
      properties:
        isOnboardingCompleted:
          type: boolean

    # TODO: add other fields
    ParentProfile:
      nullable: true
      type: object
      properties:
        isOnboardingCompleted:
          type: boolean

    OnboardingResponse:
      type: object
      required:
        - activeRole
      properties:
        activeRole:
          type: string
          enum: [TRAINER, TRAINEE, PARENT, ADMIN]

    UpdateLanguageRequest:
      type: object
      required:
        - preferredLang
      properties:
        preferredLang:
          type: string
          enum: [en, ua, pl]

    UpdateRoleRequest:
      type: object
      required:
        - role
      properties:
        role:
          type: string
          enum: [TRAINER, TRAINEE, PARENT, ADMIN]

    InitializeRoleRequest:
      type: object
      required:
        - role
      properties:
        role:
          type: string
          enum: [TRAINER, TRAINEE, PARENT, ADMIN]

    InitializeRoleResponse:
      type: object
      required:
        - isFirstTime
      properties:
        isFirstTime:
          type: boolean
          example: true

  responses:
    InvalidToken:
      description: Invalid token
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid token"

    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid input data"

    InvalidRole:
      description: Invalid role
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid role or insufficient permissions"
